version: '3.8'

services:

  mongo:
    image: mongo:latest
    restart: always
    container_name: mongoDB
    hostname: host-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: contrasena
      MONGO_INITDB_DATABASE: mongoDATABASE
    ports:
      - 27017:27017

    volumes:
      - ./mongo/:/etc/mongo




#  mongo-express:
#    image: mongo-express
#    restart: always
#    ports:
#      - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: example
#      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/